name: pr-deployment
run-name: ${{github.actor}} updated
on:
  push:
    branches:
      - dev
  pull_request:
jobs: 
  compile:
    name: Compilation Step
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Compile sketch for Arduino UNO
        uses: arduino/compile-sketches@v1
        with:
            fqbn: arduino:avr:uno
            sketch-paths: |
              ./src
            cli-compile-flags: |
              - --output-dir
              - build
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: build/*.hex
